name: "Update POT Files "

#on: workflow_dispatch
on: [push, workflow_dispatch]

jobs:
  UpdatePOT:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: get gettext
        run: sudo apt install -y gettext

        #get Repository basename, use with ${{ env.REPO_NAME }}
      - name: get-name
        run: |
          echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

        # check out target repository
      - name: checkout target repository (this)
        uses: actions/checkout@v3
        with: 
          repository: $GITHUB_REPOSITORY
          path: $GITHUB_REPOSITORY

        # check out destination repository
      - name: checkout gettext-locale
        uses: actions/checkout@v3
        with: 
          repository: kanboard-ng/gettext-locale
          path: kanboard-ng/gettext-locale

        # fetch target repository for new translations
      - name: fetch translations
        run: 
          find ./$GITHUB_REPOSITORY/ -type f -name "*.php" | 
          xargs xgettext -o kanboard-ng/gettext-locale/${{ env.REPO_NAME }}.pot -L PHP -kt -ke --from-code=UTF-8 --add-comments

      # commit to destination repository
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: kanboard-ng/gettext-locale

